title: insanj.com
description: > # this means to ignore newlines until "baseurl:"
  ğŸ¥ i make siege videos every week
  ğŸš‚ i'm also a very active software developer, on the hunt for new projects
  ğŸ’– support me on patreon and let's make something awesome
permalink: pretty
baseurl: ""
url: ""
site-twitter: insanj
author: Julian Weiss
author-img: summer.jpg # add your photo
about-author: >
  <p>ğŸ¥<br/>i make siege videos every week</p>
  <p>ğŸš‚<br/>active software developer, on the hunt for new projects</p>
  <p>ğŸ’–<br/>support me on patreon and let's make something awesome</p>
social-twitter: insanj 
social-github: insanj
social-linkedin: insanj
social-email: me@insanj.com
social-angellist: insanj
social-youtube: insanj

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 18
paginate_path: "/page/:num"
permalink: /:title/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

sass:
  sass_dir: _sass
  style: :compressed

sidebar_page_links:
- title: "ğŸŒ Portfolio"
  url: "http://insane.works"
- title: "ğŸš€ Patreon"
  url: "http://patreon.com/insanj"
- title: "ğŸ‘‹ Resume"
  url: "http://julianresume.site"

show-fancy-background: true
