title: insanj.com
description: > # this means to ignore newlines until "baseurl:"
  ğŸ‘‹ freelancing & looking for work in philly 
  ğŸ“± iOS entrepreneur 
  ğŸ¨ design pragmatist 
  ğŸ¼ music enthusiast 
  ğŸ“ college grad 
permalink: pretty
baseurl: ""
url: ""
site-twitter: insanj
author: Julian Weiss
author-img: summer.jpg # add your photo
about-author: >
  <p>ğŸ‘‹ freelancing & looking for work in philly</p>
  <p>ğŸ“± iOS entrepreneur</p>
  <p>ğŸ¨ design pragmatist</p>
  <p>ğŸ¼ music enthusiast</p> 
  <p>ğŸ“ college grad</p>
social-twitter: insanj 
social-github: insanj
social-linkedin: insanj
social-email: me@insanj.com
social-angellist: insanj

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 18
paginate_path: "/page/:num"
permalink: /:title/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

sass:
  sass_dir: _sass
  style: :compressed

show-fancy-background: true
